Feature/members only
jpdf00/members-only pull request #1
Opened 2021-02-26 20:53 UTC by jpdf00

In this project, we implemented authentication systems so users can only access areas of a site they are authorized to.

- If no user is logged, the index page shows Sign up(for new users), login (for registered users), and a list of posts with "Anonymous" as the post creator.
- If the user is logged, the index page shows the users name(with a link for editing), logout (to end the session), new post(with a link to create a new post), and a list of posts with the name and username of their respective creators.

2021-02-27 10:39 UTC, lekegitrepo requested changes
## Status: Changes Required! :recycle:
### Hi @jpdf00 :clap: :clap:
#### You did an awesome job, you deserve :+1: for what you have did so far. However, there are some requirements missing/not implemented correctly. Check my comments below :point_down:

#### PostController:
 - it should use `before_action` to restrict access to the `:new` and `:create` methods. In this case the `:new` method is missing in the `before_action` filter.
 - `:new` should initialize an empty post `@post = Post.new`

#### _Reviewed by Temitayo Adeleke_

2021-02-28 04:17 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Hello @jpdf00 and @anapdh , Great job! 👏  Both of you have done well on this project.

However, there are still some changes that are necessary for this project to be approved.
Let us quickly add some finishing touches and request another review.

- [x] Add validations to your post model, I should not be able to create an empty post

- [ ] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright)
I have gone ahead and made some comments on your codebase see affected files below:

**Don't know where to start or how to?** See  [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4) 

- [ ] Do not forget to add `yarn` to your getting started instructions, perfect after the `bundle install`. I couldn't run the project without running `yarn`

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2021-02-28 04:17 UTC, acushlakoncept commented on app/views/layouts/application.html.erb
> +    <% end %>
There should be absolutely NO logic in views.

2021-02-28 04:17 UTC, acushlakoncept commented on app/views/posts/_form.html.erb
> +<% end %>
There should be absolutely NO logic in views.

2021-02-28 04:17 UTC, acushlakoncept commented on app/views/posts/index.html.erb
> +</ul>
There should be absolutely NO logic in views.

2021-03-01 18:03 UTC, MahmoudBakr23 requested changes
# **Changes Required 🛑♻**

<hr>

Hello there, great job you've done so far on this project and on the required changes. You refactored the logic of your views, put the before_action in perfect usage. So, well done. However, there are still a few more fixes to make in order to get it completely perfect :)

- [x] Since you're limiting the posts route resources to only index, new, and create, there's no need to show, edit, update, and destroy methods in the controller. They're not even working! Please remove them and their related code such as the set_post method from your controller and view related files.
![posts_routes_requirement](https://user-images.githubusercontent.com/47625407/109538763-24d6bc80-7ac9-11eb-8fd4-da07b2aee7b6.png)

- [ ] Your readme file misses the ```rails db:create``` before the ```rails db:migrate``` CLI

<hr>

Kindly make the required changes, then ask for another review.
Good luck and happy coding 👨‍💻💻

2021-03-01 21:55 UTC, blackpintz approved these changes
# Status: Approved 🎉 

**Congratulations team 👏. Good luck with your next project 😃.**

2021-03-01 22:09 UTC, merged